### ISSUE TITLE
Add integration tests workflow

### ISSUE THREAD

**Issue by SHAcollision** [pubky/pubky-nexus#14]
Add a CI workflow `.github/workflows/test.yml` that:
1. Starts up the services (neo4j, redis) using docker.
2. Runs the scripts to populate the graph with the example data.
3. Runs the service `cargo run --bin pubky-nexus-service`
4. Once the service is ready, runs the tests `cargo test`

- It should run on PR's targetted to `main` branch and block merge if tests do not pass.
- Optionally: it could use matrix strategy to build on `stable` and `nightly` rust.

```yml
# for example...

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        rust: [stable, nightly]

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
# ....
```
